site_name: Stencil Dev
site_description: Personal infrastructure portfolio and technical notes
site_url: https://dstencil.com

theme:
  name: material
  features:
    - navigation.tabs
  # Dark Mode
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode
      primary: black
      accent: indigo

  # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
      primary: black
      accent: indigo

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Homelab: homelab/index.md
  - Notes: notes/index.md
  - Contact: contact.md